configDb:
  dbHost: web-db
  dbPort: 5432
  dbUser: web
  dbPass: this_is_web
  dbDatabase: web

configPorts: 11000

configOrm: 50

configRaw:
  hasqlSettingsPoolN: 50
  hasqlSettingsTm: 0.5

configPool:
  poolSettingsStripesN: 1
  poolSettingsTimeToOpen: 0.5
  poolSettingsResPerStripe: 1

configKatip: katip

configEkg:
  ekgHost: server
  ekgPort: 8000