version: '3.2'
services:

  database:
    image: postgres:latest
    container_name: "edge-node-server-db"
    restart: 'always'
    expose:
     - 5432
    ports:
      - '5432:5432'
    environment:
      - DB_USER=$DBUSER
      - DB_PASSWORD=3190d261d186aeead3a8deec202737c7775af5c8d455a9e5ba958c48b5fd3f59
      - DB_DATABASE=$DATABASE
      - POSTGRES_PASSWORD=264c0424e4bd463a7d02b9db6896143e1a96cd1c52511119f839d2bc9c934241
      - POSTGRES_USER=postgres
    volumes:
      - ${PWD}/deploy/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - pg_data_db:/var/lib/postgresql/data
    networks:
      edgeNode:
        ipv4_address: 172.20.0.7

  server:
    image: registry.gitlab.com/edgenode2/server:$TAG
    container_name: "edge-node-server"
    links:
      - database
      - storage
    depends_on:
      - database
      - storage
    expose:
     - 25
     - 12000
     - 8000
    ports:
      - "12000:12000"
      - "8000:8000"
      - "25:25" 
    networks:
      edgeNode:
        ipv4_address: 172.20.0.6
  
  storage:
    image: minio/minio:latest
    container_name: "edge-node-file-storage"
    restart: 'always'
    expose:
      - 9000
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    networks:
      edgeNode:
        ipv4_address: 172.20.0.5

networks:
  edgeNode:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24     

volumes:
  pg_data_db: {}
  minio_data: {}

# vim: et:sw=2
