version: '3.2'
services:

  server-db:
    image: postgres
    container_name: "edge-node-server-db"
    restart: 'always'
    expose:
     - 5432
    ports:
      - '5432:5432'
    environment:
      - DB_USER=web
      - DB_PASSWORD=this_is_web
      - DB_DATABASE=web
      - POSTGRES_PASSWORD=this_is_postgres
      - POSTGRES_USER=postgres
    volumes:
      - ${PWD}/deploy/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - pg_data_db:/var/lib/postgresql/data
    networks:
      - edgeNode

  server:
    image: registry.gitlab.com/edgenode2/server:latest
    container_name: "edge-node-server"
    links:
      - server-db
    depends_on:
      - server-db
    expose:
     - 25
    ports:
      - "12000:12000"
      - "8000:8000"
      - "25:25" 
    networks:
      - edgeNode
  
  storage: 
    image: minio/minio:latest
    container_name: "edge-node-file-storage"
    restart: 'always'
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    networks:
      - edgeNode

networks:
  edgeNode:

volumes:
  pg_data_db: {}
  minio_data: {}

# vim: et:sw=2
