name:                edgeNode-server
version:             0.1.0.0
github:              "githubuser/web"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"
ghc-options:
  - -threaded
  - -rtsopts
  # - -with-rtsopts=-N
  # - -with-rtsopts=-T
  # - -with-rtsopts=-n4m
  # - -with-rtsopts=-A32m
  # - -with-rtsopts=-qb0
  # - -with-rtsopts=-I0
  # - -with-rtsopts=-s
  - -O2
  - -Werror
  - -fwarn-unused-imports
  - -Wredundant-constraints
  - -Wduplicate-exports
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-fields
  - -Wmissing-exported-signatures
  - -Wunused-binds
  - -Wwrong-do-bind
  - -Wcpp-undef
  - -Wunused-do-bind
  - -Wunused-pattern-binds
  - -Wtabs
  - -Wmissing-pattern-synonym-signatures
  - -XMonadFailDesugaring
  - -XOverloadedStrings
  - -ddump-splices

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/web#readme>

dependencies:
- base >= 4.7 && < 5

library:
  dependencies:
    - tasty
    - tasty-hspec
    - tasty-hunit
    - tasty-html
    - aeson
    - lens
    - lens-aeson
    - async
    - lifted-async
    - monad-control
    - text
    - bytestring
    - containers
    - template-haskell
    - hslogger
    - hspec-pg-transact
    - ginger
    - groundhog
    - groundhog-th
    - groundhog-postgresql
    - yaml
    - extra
    - colorful-monoids
    - hspec
    - resource-pool
    - tmp-postgres
    - directory
    - filepath
    - time
    - pretty-simple
    - brick
    - process
    - random
    - servant
    - servant-server
    - katip
    - transformers-base
    - mtl
    - transformers
    - servant-server
    - warp
    - rotating-log
    - doctest
    - doctest-discover
    - tasty-discover
    - servant-websockets
    - websockets
    - hasql
    - hasql-pool
    - ekg
    - exceptions
    - regex-with-pcre
    - validation
    - pretty-tree
    - pwstore-fast 
    - servant-swagger-ui
    - servant-swagger-ui-core
    - servant-swagger
    - swagger2
    - wai-app-static
    - aeson-injector
    - exception-hierarchy
    - servant-auth
    - servant-auth-server
    - servant-auth-swagger
    - jose
    - either
    - generic-lens
    - scientific
    - proto3-suite
    - proto3-wire
    - vector
    - deepseq
    - QuickCheck
    - safe-exceptions
    - wai
    - casing
    - lifted-base
    - data-default-class
    - postgresql-error-codes
    - string-interpolate
    - http-client
    - http-client-tls
    - memory
    - http-types
  source-dirs:
    - backend/core
    - backend/extended
    - backend/proto
    - test
    - app

executables:
  edge-node-server:
    main:                app.hs
    source-dirs:         prog
    dependencies:
    - edgeNode-server

tests:
  tasty:
    main:                test.hs
    source-dirs:         prog
    dependencies:
    - edgeNode-server
  doctest:
    main:             doctest.hs
    source-dirs:      prog
    dependencies:
    - edgeNode-server
    - doctest-discover