version: '3.2'
services:

  server-db:
    image: postgres
    container_name: "edge-node-server-db"
    restart: 'always'
    ports:
      - '5433:5432'
    environment:
      - DB_USER=${USER_VAR}
      - DB_PASSWORD=${PWD_VAR}
      - DB_DATABASE=${DB_VAR}
      - DB_SCHEMA=${SCHEMA_VAR}
      - POSTGRES_PASSWORD=${PG_PWD_VAR}
      - POSTGRES_USER=${PG_USER_VAR}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - pg_data_db:/var/lib/postgresql/data
    build: './db'
    networks:
      - edgeNode

  server:
    build: ./server
    container_name: "edge-node-server"
    links:
      - server-db
    depends_on:
      - server-db
    ports:
      - "12000:12000"
      - "8000:8000"    
    networks:
      - edgeNode
  
networks:
  edgeNode:

volumes:
  pg_data_db: {}

# vim: et:sw=2
