configDb:
  dbHost: 172.20.0.7
  dbPort: 5432
  dbUser: sonny
  dbPass: 3190d261d186aeead3a8deec202737c7775af5c8d455a9e5ba958c48b5fd3f59
  dbDatabase: edgenode

configSwagger: 
  swaggerHost: 136.243.173.173
  swaggerPort: 12000

configHasql:
  hasqlSettingsPoolN: 50
  hasqlSettingsTm: 0.5
  hasqlSettingsResPerStripe: 1

configKatip: 
  katipPath: katip
  katipSeverity: DebugS
  katipVerbosity: V3 
  katipEnv: production

configAuth: 
  authJwk: symmetric.jwk
  authIsAuthEnabled: true
  authUserId: 1

configService:
  serviceApiKeys: 
   - [google, AIzaSyCBwZWJtSwz4dN8suya3YLZMJJjodr3zVM]

configMinio:
  minioAccessKey: AKIAIOSFODNN7EXAMPLE
  minioSecretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  minioBucketPrefix: edgenode
  minioHost: http://172.20.0.5
  minioPort: "9000"